accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import CustomAuthForm
from .views import *

app_name='accounts'

urlpatterns = [
    # Sign up & Sign in
    path('', signup, name='index'),
    path('redirect', login_redirect, name='redirect'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=CustomAuthForm), name='login'),

    # Password reset
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # Profile
    path('user/<int:pk>/', UserDetailView.as_view(), name='profile_detail'),
    path('user/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('user/<int:pk>/invite/',      InviteUpdateView.as_view(),    name='invite_update'),
    path('user/<int:pk>/invite/all/',  InviteUpdateAllView.as_view(), name='invite_update_all'),
]

api/urls.py
from django.urls import path

from .views import ListTask

urlpatterns = [
    path('appsite/', ListTask.as_view()),
]

appsite/urls.py
from django.urls import path

from . import views

app_name='appsite'

urlpatterns = [
    ### Profile ###


    path('user/<int:pk>/list/create/', views.ListCreateView.as_view(),      name='list_create'),

    ### List ###
    path('list/<int:pk>/',              views.ListDetailView.as_view(),   name='list_detail'),
    path('list/<int:pk>/update/',       views.ListUpdateView.as_view(),   name='list_update'),
    path('list/<int:pk>/delete/',       views.ListDeleteView.as_view(),   name='list_delete'),
    path('list/<int:pk>/menu/',         views.ListMenuTemplate.as_view(), name='list_menu'),
    path('list/<int:pk>/untrack/',      views.ListUntrackView.as_view(),  name='list_untrack'),
    path('list/<int:pk>/jobs/',         views.JobUpdateView.as_view(),    name='job_update'),
    path('list/<int:pk>/task/create/',  views.TaskCreateView.as_view(),   name='task_create'),
    path('list/<int:pk>/tag/create/',   views.TagCreateView.as_view(),    name='tag_create'),
    path('list/<int:pk>/tag/follow/',   views.TagFollowView.as_view(),    name='tag_follow'),
    path('list/<int:pk>/tag/unfollow/', views.TagUnfollowView.as_view(),  name='tag_unfollow'),

    ### Task ###
    path('task/<int:pk>/update/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),

    ### Tag ###
    path('tag/<int:pk>/add/', views.TagAddView.as_view(), name='tag_add'),
]

opus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('app/', include('appsite.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('favicon.ico', RedirectView.as_view(url="static/images/favicon.png")), # Fix favicon
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver

from .avatars.get_avataaars import generate_avatar


# Tabela complementar de usuários
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.URLField(
        default="",
        max_length=510,
        null=True
    )
    description = models.TextField(
        default="Adicione uma descrição pra completar seu perfil.",
        max_length=255,
        null=True
    )
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.picture:
            self.picture = generate_avatar()
        super(Profile, self).save(*args,**kwargs)

@receiver(models.signals.post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(models.signals.post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


# Transforma labels em placeholders
class PlaceholderMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        field_names = list(self.fields.keys())
        for field_name in field_names:
            field = self.fields.get(field_name)
            field.widget.attrs.update({'placeholder' : field.label})


class UserForm(PlaceholderMixin, UserCreationForm):
    class Meta:
        model = User

        fields = [
            'username',
            'email',
        ]
        labels = {
            'username' : 'Usuário',
            'email'    : 'E-mail',
        }


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'placeholder' : 'Usuário'})
    )
    password = forms.CharField(
        widget=forms.widgets.PasswordInput(attrs={'placeholder' : 'Senha'})
    )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile

        fields = [
            'picture',
            'description'
        ]
        labels = {
            'picture' : 'Foto (URL)',
            'type' : 'Descrição'
        }

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import generic
from django.views.decorators.csrf import csrf_protect

from appsite.models import Job, List

from .forms import ProfileForm, UserForm
from .models import Profile
from .tokens import account_activation_token


@login_required
def login_redirect(request):
    return redirect('accounts:profile_detail', pk=request.user.pk)

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)

            mail_subject = 'Activate your Opus account.'
            message = render_to_string('accounts/acc_active_email.html', {
                'user'  : user,
                'domain': current_site.domain,
                'uid'   : urlsafe_base64_encode(force_bytes(user.pk)),
                'token' : account_activation_token.make_token(user),
            }, request=request) # request=request is to use csrf_token
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.content_subtype = "html"
            email.send()

            return HttpResponseRedirect(reverse_lazy('login'))
    else:
        form = UserForm()
    return render(request, 'registration/index.html', {'form' : form})


@csrf_protect
def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        login(request, user)

        return HttpResponseRedirect( reverse_lazy('accounts:profile_detail', args=(user.id, )) )
    else:
        return HttpResponse('Activation link is invalid!')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('login')


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    template_name = 'profile/detail.html'

    # Envia para o template:
    # - Qual usuário está logado e qual perfil foi acessado
    # - As listas do perfil acessado
    def get_context_data(self, **kwargs):
        current_user = self.request.user
        profile_user = User.objects.get(pk=self.kwargs['pk'])

        lists_id_pending = Job.objects.filter(user=profile_user, active_invite=True).values_list('list')
        lists_id_confirmed = Job.objects.filter(user=profile_user, active_invite=False).values_list('list')

        lists_pending = List.objects.filter(pk__in=lists_id_pending)
        lists_confirmed = List.objects.filter(pk__in=lists_id_confirmed)

        context = {
            'current_user'    : current_user,
            'profile_user'    : profile_user,
            'lists_pending'   : lists_pending,
            'lists_confirmed' : lists_confirmed,
        }

        return context


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profile/update.html'

    def get_success_url(self):
        return reverse_lazy('accounts:profile_detail', args=(self.request.user.id, ))


class InviteUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'accounts/profile/detail.html'
    model = Job

    def post(self, request, *args, **kwargs):
        post_data = request.POST.dict() # Gets the form's data
        response, list_id = list(post_data.keys())[1: ]

        list_obj = List.objects.get(pk=list_id)
        user = User.objects.get(pk=self.kwargs['pk'])
        job = Job.objects.get(user=user, list=list_obj)

        if response == 'accept':
            job.active_invite = False
            job.save()
        elif response == 'refuse':
            job.delete()
        else:
            raise ValueError("Expected 'accept' or 'refuse' as response.")
        return HttpResponseRedirect( reverse_lazy('accounts:profile_detail', args=(self.kwargs['pk'], )) )


class InviteUpdateAllView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'accounts/profile/detail.html'
    model = Job

    def post(self, request, *args, **kwargs):
        post_data = request.POST.dict() # Gets the form's data
        response = list(post_data.keys())[1]

        user = User.objects.get(pk=self.kwargs['pk'])
        jobs = Job.objects.filter(user=user, active_invite=True)

        if response == 'accept':
            for job in jobs:
                job.active_invite = False
                job.save()
        elif response == 'refuse':
            jobs.delete()
        else:
            raise ValueError("Expected 'accept' or 'refuse' as response.")
        return HttpResponseRedirect( reverse_lazy('accounts:profile_detail', args=(self.kwargs['pk'], )) )

accounts/templates/profile/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ profile_user.username }} {% endblock title %}

{% block content %}

<header class="white-box profile-header">
    <div class="profile-pic-mask">
        <img src="{{ profile_user.profile.picture }}" alt="profile-pic" />
    </div>
    <section class="profile-text">
        <div class="profile-header-upper">
            <h1 class="color-light-gray">@</h1><h1>{{ profile_user.username }}</h1>
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'logout' %}">
                    <button class="blue-button profile-logout-button">Sair</button>
                </a>
            {% else %}
            <a href="{% url 'accounts:profile_detail' current_user.id %}">
                <button class="blue-button profile-logout-button">Voltar</button>
            </a>
            {% endif %}
        </div>
        <p>{{ profile_user.profile.description }}</p>
    </section>
    {% if current_user.id == profile_user.id %}
        <a href="{% url 'accounts:profile_update' profile_user.profile.id %}">
            <button class="profile-config-button">
                <img class="user-config-cog" src="https://i.ibb.co/PrLfbbR/cog.png" alt="profile-config-icon" />
            </button>
        </a>
    {% endif %}
</header>


<article class="profile-menus">

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-blue1">
            <h1>Listas</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'appsite:list_create' profile_user.id %}">
                    <button class="blue-button create lists-menu-button">Criar lista</button>
                </a>
            {% endif %}
        </div>
        {% if lists_confirmed %}
            <div class="lists-menu-cards">
                {% for list in lists_confirmed %}

                {% include 'components/list_card.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-blue1">
                <p>Ainda não existem listas criadas ou seguidas.</p>
            </div>
        {% endif %}
    </section>

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-pink">
            <h1>Convites</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <form class="lists-menu-buttons-form" method="POST" action="{% url 'accounts:invite_update_all' profile_user.id %}">
                    {%csrf_token%}
                    <input type="submit" class="accept lists-menu-button" name="accept" value="Aceitar tudo" />
                    <input type="submit" class="refuse lists-menu-button" name="refuse" value="Recusar tudo" />
                </form>
            {% endif %}
        </div>
        {% if lists_pending %}
            <div class="lists-menu-cards">
                {% for list in lists_pending %}

                {% include 'components/list_card_invite.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name
                    prof_user_id=profile_user.id
                    curr_user_id=current_user.id %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-pink">
                <p>Sem novos convites por hoje!</p>
            </div>
        {% endif %}

    </section>

</article>

{% endblock content %}

accounts/templates/profile/update.html
{% extends 'base.html' %}

{% block title %} Editar: @{{ user.username }} {% endblock title %}

{% block content %}

<article class="white-box form-box edit-profile-box">
    <header class="form-box-title criador">
        <h1>Editar perfil</h1>
    </header>

    <form method="POST">
        {% csrf_token %}
        <div class="form-box-field">
            {{ form.picture.label }}
            {{ form.picture }}
        </div>
        <div class="form-box-field">
            {{ form.description.label }}
            {{ form.description }}
        </div>
        <div class="form-box-buttons">
            <a href="{% url 'accounts:profile_detail' user.id %}">
                <button class="gradient-button secondary button" type="button">Voltar</button>
            </a>
            <button class="gradient-button primary-button" type="submit">Salvar</button>
        </div>
    </form>
</article>

{% endblock content %}