accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import CustomAuthForm
from .views import *

app_name='accounts'

urlpatterns = [
    # Sign up & Sign in
    path('', signup, name='index'),
    path('redirect', login_redirect, name='redirect'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=CustomAuthForm), name='login'),

    # Password reset
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # Profile
    path('user/<int:pk>/', UserDetailView.as_view(), name='profile_detail'),
    path('user/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('user/<int:pk>/invite/',      InviteUpdateView.as_view(),    name='invite_update'),
    path('user/<int:pk>/invite/all/',  InviteUpdateAllView.as_view(), name='invite_update_all'),
]

api/urls.py
from django.urls import path

from .views import ListTask

urlpatterns = [
    path('appsite/', ListTask.as_view()),
]

appsite/urls.py
from django.urls import path

from . import views

app_name='appsite'

urlpatterns = [
    ### Profile ###


    path('user/<int:pk>/list/create/', views.ListCreateView.as_view(),      name='list_create'),

    ### List ###
    path('list/<int:pk>/',              views.ListDetailView.as_view(),   name='list_detail'),
    path('list/<int:pk>/update/',       views.ListUpdateView.as_view(),   name='list_update'),
    path('list/<int:pk>/delete/',       views.ListDeleteView.as_view(),   name='list_delete'),
    path('list/<int:pk>/menu/',         views.ListMenuTemplate.as_view(), name='list_menu'),
    path('list/<int:pk>/untrack/',      views.ListUntrackView.as_view(),  name='list_untrack'),
    path('list/<int:pk>/jobs/',         views.JobUpdateView.as_view(),    name='job_update'),
    path('list/<int:pk>/task/create/',  views.TaskCreateView.as_view(),   name='task_create'),
    path('list/<int:pk>/tag/create/',   views.TagCreateView.as_view(),    name='tag_create'),
    path('list/<int:pk>/tag/follow/',   views.TagFollowView.as_view(),    name='tag_follow'),
    path('list/<int:pk>/tag/unfollow/', views.TagUnfollowView.as_view(),  name='tag_unfollow'),

    ### Task ###
    path('task/<int:pk>/update/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),

    ### Tag ###
    path('tag/<int:pk>/add/', views.TagAddView.as_view(), name='tag_add'),
]

opus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('app/', include('appsite.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('favicon.ico', RedirectView.as_view(url="static/images/favicon.png")), # Fix favicon
]

appsite/forms.py
import requests
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm, widgets

from .models import Job, List, Tag, Task


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            'user',
            'type'
        ]
        labels = {
            'user' : 'Usuário',
            'type' : 'Cargos'
        }

    def __init__(self, *args, **kwargs):
        # Extrai dados enviados pela JobUpdateView
        self.user = kwargs.pop('user')       # Usuário atual da página
        self.list_id = kwargs.pop('list_id') # Id da lista atual

        super(JobForm, self).__init__(*args, **kwargs)

        list_obj = List.objects.get(pk=self.list_id) # Obtém a lista atual

        # Obtém todos os ids de seguidores e administradores
        subordinates_job = Job.objects.filter(list=list_obj, type__in=[2, 3])
        subordinates_id = subordinates_job.values_list('user', flat=True)

        # Define as transições de cargo possíveis
        jobs_transitions = [(2, 'Seguidor'), (3, 'Administrador')]

        # Seleciona apenas os usuários subordinados
        self.fields['user'].queryset = User.objects.filter(pk__in=subordinates_id)
        self.fields['type'] = forms.ChoiceField(choices=jobs_transitions)


class ListForm(ModelForm):
    class Meta:
        model = List
        fields = [
            'name',
            'symbol',
            'picture',
            'description',
            'color',
        ]
        labels = {
            'name' : 'Nome',
            'symbol' : 'Ícone',
            'color' : 'Cor',
            'picture' : 'Imagem (URL)',
            'description' : 'Descrição',
        }
        widgets = {
            "color": widgets.TextInput(attrs={"type": "color"}),
        }

    def __init__(self, *args, **kwargs):
        super(ListForm, self).__init__(*args, **kwargs)
        self.fields['picture'].initial = requests.get('https://source.unsplash.com/1920x1080/?work').url


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'due_date'
        ]
        labels = {
            'name' : 'Tarefa',
            'due_date' : 'Entrega'
        }
        widgets = {
            "due_date": forms.SelectDateWidget(),
        }


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = [
            'name',
            'value'
        ]
        labels = {
            'name' : 'Coluna',
            'value' : 'Tag'
        }


class InviteForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            'user'
        ]
        labels = {
            'user' : 'Convidado'
        }

appsite/views.py
from collections import defaultdict

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from .forms import JobForm, ListForm, TagForm, TaskForm
from .models import Follow, Job, List, Tag, Task

# ====== #
# CREATE #
# ====== #

class ListCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'appsite/list_create.html'
    form_class = ListForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # Gets default context data
        context['user_id'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        self.object = form.save() # Saves the list to the database and set it as the view's object

        # Links the creator to his list in the database
        job = Job(active_invite=False, list_id=self.object.id, user_id=self.request.user.id, type=4)
        job.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('appsite:list_detail', args=(self.object.id, ))


class TagCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "appsite/tag_create.html"
    form_class = TagForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_id'] = self.kwargs['pk']
        return context

    def form_valid(self, form):
        self.object = form.save() # Saves the tag to the database and set it as the view's object

        # Links the tag to its list in the database
        list_id = self.kwargs['pk']
        list = List.objects.get(pk=list_id)
        tag = Tag.objects.get(pk=self.object.id)
        follow = Follow(list=list, tag=tag, source_id=list_id)
        follow.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('appsite:tag_create', args=(self.kwargs['pk'], ))


class TagFollowView(LoginRequiredMixin, generic.CreateView):
    template_name = 'appsite/tag_follow.html'
    form_class = TagForm # Throwable

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # Gets default context data
        current_list = List.objects.get(pk=self.kwargs['pk'])
        current_user = self.request.user

        # Gets all lists where the current user is at least an
        # administrator and prevents a list from following itself
        jobs = Job.objects.filter(user=current_user, type__gte=3)
        lists_ids = jobs.values_list('list_id', flat=True)
        lists = List.objects.filter(pk__in=lists_ids).exclude(pk=current_list.id)

        # Gets and sorts all unique tags in list
        tags = current_list.tag_set.all().distinct()
        # Dictionary of lists: create or append
        tags_dict = defaultdict(list)
        for tag in tags:
            tags_dict[tag.name].append(tag)

        context['source_list'] = current_list
        context['source_tags'] = dict(tags_dict)
        context['user_lists']  = lists
        return context

    def post(self, request, *args, **kwargs):
        # Gets the form's data and removes csrf token
        post_data = list( dict(request.POST.lists()).keys() )
        post_data = post_data[1: ]

        # POST validation
        if not post_data: # The user selected nothing
            messages.error(request, "Selecione uma e lista e pelo menos uma tag.")
            return super().post(request, *args, **kwargs)

        elif post_data[0][0] != 'l': # The user doesn't select a list
            messages.error(request, "Selecione uma lista.")
            return super().post(request, *args, **kwargs)

        elif len(post_data) < 2: # The user selected a list, but no tags
            messages.error(request, "Selecione pelo menos uma tag.")
            return super().post(request, *args, **kwargs)

        # Gets all ids in POST and sorts them
        ids = [int(id[1: ]) for id in post_data]
        to_list_id  = ids[0]                     # The ID of destiny list
        tags_ids    = ids[1: ]                   # The IDs of followed tags
        src_list_id = self.kwargs['pk']          # The ID of source list

        to_list = List.objects.get(pk=to_list_id)
        src_list = List.objects.get(pk=src_list_id)
        tags = Tag.objects.filter(pk__in=tags_ids)

        # Gets all tasks in the followed list with the given tag
        for tag in tags:
            tasks = tag.task.filter(list_id=src_list_id)
            # Copies each of these tasks to the destiny list if the original_id permits
            for task in tasks:
                if not to_list.task_set.filter(original_id=task.original_id):
                    task_copy = Task.objects.create(list_id=to_list_id, original_id=task.original_id, name=task.name, due_date=task.due_date, done=False)
                    task_copy.save()
                    # Links the followed tags from the original task to the task_copy
                    intersection = list( set(task.tag_set.filter()) & set(tags) )
                    for tag_copy in intersection:
                        tag_copy.task.add(task_copy)

            # Links user to source list if the tag hasn't been followed by him yet
            Follow.objects.get_or_create(list=to_list, tag=tag, source_id=src_list_id)

        # If the user is a guest, then becomes a follower
        if Job.objects.filter(list=src_list, user=request.user, type=1):
            job = Job.objects.get(list=src_list, user=request.user)
            job.active_invite = False
            job.type = 2
            job.save()
        return HttpResponseRedirect( reverse_lazy('appsite:list_detail', args=(src_list_id, )) )


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'appsite/task_create.html'
    form_class = TaskForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # Gets default context data
        context['list'] = List.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        current_list = List.objects.get(pk=self.kwargs['pk'])
        self.object = form.save(commit=False) # Set the task as the view's object along with user-inputted fields
        self.object.list = current_list       # Links the task to the current list
        self.object.save()                    # Saves the task to the database
        # There's no need to set the original_id because the task's model will handle it (see appsite/models.py)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('appsite:tag_add', args=(self.object.id, ))


class TagAddView(LoginRequiredMixin, generic.CreateView):
    template_name = 'appsite/tag_add.html'
    form_class = TaskForm # Throwable

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # Gets default context data

        # Gets and sorts all unique tags in list
        task = Task.objects.get(pk=self.kwargs['pk'])
        current_list = List.objects.get(pk=task.list_id)
        tags = current_list.tag_set.all().distinct()
        # Dictionary of lists: create or append
        tags_dict = defaultdict(list)
        for tag in tags:
            tags_dict[tag.name].append(tag)

        context['task'] = task
        context['tags'] = dict(tags_dict)
        context['user'] = self.request.user
        return context

    def post(self, request, *args, **kwargs):
        # Gets the form's data and removes csrf token
        post_data = list( dict(request.POST.lists()).keys() )
        post_data = post_data[1: ]

        # Gets the tags from the form's data
        tags_ids = [int(tag_id) for tag_id in post_data]
        tags = Tag.objects.filter(pk__in=tags_ids)

        # Links the task and the tags
        task = Task.objects.get(pk=self.kwargs['pk'])
        for tag in tags:
            tag.task.add(task)

        # Propagates the task to other lists that follow any of these tags
        src_list = List.objects.get(pk=task.list_id)
        followers = Follow.objects.filter(tag_id__in=tags_ids, source_id=src_list.id).exclude(list_id=src_list.id).distinct()
        self.propagate_tasks(followers, task, tags)
        return HttpResponseRedirect( reverse_lazy('appsite:list_detail', args=(src_list.id, )) )

    def propagate_tasks(self, followers, task, tags):
        """
        Custom recursive method responsible to deep copy a task to its followers, based on the added tags.

            Params:
                followers (QuerySet): all unique Follow instances that relate a source list to its followers
                task      (QuerySet): the Task instance which had tags added to
                tags      (QuerySet): all added Tag instances
            Retuns:
                None
        """
        for follow in followers:
            src_list = List.objects.get(pk=follow.source_id)
            to_list = List.objects.get(pk=follow.list_id)

            # If there's already a task in the to_list with the same original_id => Returns
            # Otherwise => Creates a task with the original_id plus the other fields
            if Task.objects.filter(list_id=to_list.id, original_id=task.original_id):
                return
            else:
                task_copy = Task.objects.create(
                    list_id=to_list.id,
                    original_id=task.original_id,
                    name=task.name,
                    due_date=task.due_date,
                    done=False
                )

            # Gets which tags the to_list actually follows from src_list

appsite/templates/appsite/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ profile_user.username }} {% endblock title %}

{% block content %}

<header class="white-box profile-header">
    <div class="profile-pic-mask">
        <img src="{{ profile_user.profile.picture }}" alt="profile-pic" />
    </div>
    <section class="profile-text">
        <div class="profile-header-upper">
            <h1 class="color-light-gray">@</h1><h1>{{ profile_user.username }}</h1>
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'logout' %}">
                    <button class="blue-button profile-logout-button">Sair</button>
                </a>
            {% else %}
            <a href="{% url 'appsite:detail' current_user.id %}">
                <button class="blue-button profile-logout-button">Voltar</button>
            </a>
            {% endif %}
        </div>
        <p>{{ profile_user.profile.description }}</p>
    </section>
    {% if current_user.id == profile_user.id %}
        <a href="{% url 'appsite:profile_update' profile_user.profile.id %}">
            <button class="profile-config-button">
                <img src="{% static 'images/icons/cog.svg' %}" alt="profile-config-icon" />
            </button>
        </a>
    {% endif %}
</header>


<article class="profile-menus">

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-blue1">
            <h1>Listas</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'appsite:list_create' profile_user.id %}">
                    <button class="blue-button create lists-menu-button">Criar lista</button>
                </a>
            {% endif %}
        </div>
        {% if lists_confirmed %}
            <div class="lists-menu-cards">            
                {% for list in lists_confirmed %}

                {% include 'components/list_card.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-blue1">
                <p>Ainda não existem listas criadas ou seguidas.</p>
            </div>
        {% endif %}        
    </section>

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-pink">
            <h1>Convites</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <form method="POST" action="{% url 'appsite:invite_update_all' profile_user.id %}">
                    {%csrf_token%}
                    <input type="submit" class="accept lists-menu-button" name="accept" value="Aceitar tudo" />
                    <input type="submit" class="refuse lists-menu-button" name="refuse" value="Recusar tudo" />
                </form>
            {% endif %}
        </div>
        {% if lists_pending %}
            <div class="lists-menu-cards">            
                {% for list in lists_pending %}

                {% include 'components/list_card_invite.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name
                    prof_user_id=profile_user.id
                    curr_user_id=current_user.id %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-pink">
                <p>Sem novos convites por hoje!</p>
            </div>
        {% endif %}
        
    </section>

</article>

{% endblock content %}

appsite/templates/appsite/list_detail.html
{% extends 'base.html' %}

{% block title %} {{ list.name }} {% endblock title %}

{% block content %}

<div class="list-top">
    <header class="white-box list-header">
        <div class="list-header-upper">
            <div style="background-color: {{ list.color }}" class="list-symbol">
                <h1>{{ list.symbol }}</h1>
            </div>
            <div class="list-header-info">
                <h1 class="list-title">{{ list.name }}</h1>
                <p>Criado por @{{ creator.first.username }} em {{ list.date }}</p>
            </div>
            <section class="list-header-buttons">
                {% if current_user.job_type.code == 1 %}
                    <a href="{% url 'appsite:tag_follow' list.id %}">
                        <button class="blue-button list-follow-button">Seguir</button>
                    </a>
                {% elif current_user.job_type.code >= 2 %}
                    <a href="{% url 'appsite:list_menu' list.id %}">
                        <button class="blue-button list-follow-button">Menu</button>
                    </a>
                {% endif %}
                {% if current_user.job_type.code >= 3 %}
                    <a href="{% url 'appsite:list_update' list.id %}">
                        <button class="blue-button list-edit-button">Editar</button>
                    </a>
                {% endif %}
            </section>
        </div>
        <p class="list-header-description">{{ list.description }}</p>
    </header>
    <aside class="white-box list-user-card">
        {% include 'components/user_card.html' with
            user_id=current_user.object.id
            user_picture=current_user.object.profile.picture
            user_name=current_user.object.username
            user_job=current_user.job_type.name %}
    </aside>
</div>


{% if current_user.job_type.code >= 1 %}
    <div class="list-bottom">
        <article class="list-tasks white-box">
            {% if tasks_ids %}
                {% include 'components/task_table.html' with
                    header=table_header
                    body=table_body
                    tasks_ids=tasks_ids
                    list_id=list.id
                    current_user_job_type=current_user.job_type.code %}
            {% else %}
                <div class="list-tasks-empty">
                    <p>Sem tarefas criadas até agora!</p>
                </div>
            {% endif %}
            {% if current_user.job_type.code >= 3 %}
                <a href="{% url 'appsite:task_create' list.id %}">
                    <button class="blue-button new-task-button">Nova Tarefa</button>
                </a>
            {% endif %}
        </article>

        <aside class="white-box list-social">
            <header class="list-social-header">
                <h3>Social</h3>
                {% if current_user.job_type.code >= 3 %}
                    <a href="{% url 'appsite:job_update' list.id %}">
                        <button class="list-social-jobs-button">
                            <img src="https://i.ibb.co/LvtYZdq/user-cog.png" alt="list-social-jobs-button" />
                        </button>
                    </a>
                {% endif %}
            </header>

            <section class="list-social-creator">
                <h3 class="job-title criador">Criador</h3>
                <img src="{{ creator.first.profile.picture }}" alt="social-user-pic"/>
            </section>

            <section class="list-social-admins">
                <h3 class="job-title administrador">Administradores</h3>
                {% if administrator %}
                    {% for user in administrator|slice:":4" %}
                        <img src="{{ user.profile.picture }}" alt="social-user-pic"/>
                    {% endfor %}
                {% else %}
                    <div class="list-social-empty gradient-pink2">
                        <p>A lista ainda não possui administradores.</p>
                    </div>
                {% endif %}
            </section>

            <section class="list-social-followers">
                <h3 class="job-title seguidor">Seguidores</h3>
                {% if follower %}
                    {% for user in follower|slice:":10" %}
                        <img src="{{ user.profile.picture }}" alt="social-user-pic"/>
                    {% endfor %}
                {% else %}
                    <div class="list-social-empty gradient-yellow">
                        <p>Ninguém apenas segue essa lista ainda.</p>
                    </div>
                {% endif %}
            </section>
        </aside>
    </div>
{% else %}
    <section class="white-box forbidden">
        <p>Parece que você ainda não foi convidado para acompanhar essa lista!</p>
    </section>
{% endif %}

{% endblock content %}

appsite/templates/appsite/list_menu.html
{% extends 'base.html' %}

{% block title %} {{ list.name }}: Menu {% endblock title %}

{% block content %}

<article class="white-box form-box list-menu-box">
    <section class="list-menu-follow">
        <header class="form-box-title criador">
            <h1>Seguir tags</h1>
            <p class="color-body pad-top">Interesse em algo novo? Então siga outras tags!</p>
        </header>
        <div class="form-box-buttons">
            <a href="{% url 'appsite:tag_follow' list.id %}">
                <button class="gradient-button primary-button large-button" type="button">Seguir tags</button>
            </a>
        </div>
    </section>

    {% if current_user.job_type.code == 3 or current_user.job_type.code == 4 %}
    <section class="list-menu-unfollow">
        <header class="form-box-title administrador">
            <h1>Deixar tags</h1>
            <p class="color-body pad-top">Muitas tags? Então deixe de acompanhar as que não te interessam mais!</p>
        </header>
        <div class="form-box-buttons">
            <a href="{% url 'appsite:tag_unfollow' list.id %}">
                <button class="gradient-button primary-button pink-overlay large-button" type="button">Deixar tags</button>
            </a>
        </div>
    </section>
    {% endif %}

    {% if current_user.job_type.code == 2 or current_user.job_type.code == 3 %}
        <section class="list-menu-follow">
            <header class="form-box-title seguidor">
                <h1>Deixar lista</h1>
                <p class="color-body pad-top">Nada mais do seu interesse? Talvez então seja um boa hora para partir!</p>
            </header>
            <div class="form-box-buttons">
                <a href="{% url 'appsite:list_untrack' list.id %}">
                    <button class="gradient-button primary-button yellow-overlay large-button" type="button">Deixar lista</button>
                </a>
            </div>
        </section>
    {% endif %}
    <a href="{% url 'appsite:list_detail' list.id %}">
        <button class="gradient-button secondary-button" type="button">Voltar</button>
    </a>
</article>

{% endblock content %}

appsite/templates/appsite/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ profile_user.username }} {% endblock title %}

{% block content %}

<header class="white-box profile-header">
    <div class="profile-pic-mask">
        <img src="{{ profile_user.profile.picture }}" alt="profile-pic" />
    </div>
    <section class="profile-text">
        <div class="profile-header-upper">
            <h1 class="color-light-gray">@</h1><h1>{{ profile_user.username }}</h1>
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'logout' %}">
                    <button class="blue-button profile-logout-button">Sair</button>
                </a>
            {% else %}
            <a href="{% url 'appsite:profile_detail' current_user.id %}">
                <button class="blue-button profile-logout-button">Voltar</button>
            </a>
            {% endif %}
        </div>
        <p>{{ profile_user.profile.description }}</p>
    </section>
    {% if current_user.id == profile_user.id %}
        <a href="{% url 'appsite:profile_update' profile_user.profile.id %}">
            <button class="profile-config-button">
                <img class="user-config-cog" src="https://i.ibb.co/PrLfbbR/cog.png" alt="profile-config-icon" />
            </button>
        </a>
    {% endif %}
</header>


<article class="profile-menus">

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-blue1">
            <h1>Listas</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <a href="{% url 'appsite:list_create' profile_user.id %}">
                    <button class="blue-button create lists-menu-button">Criar lista</button>
                </a>
            {% endif %}
        </div>
        {% if lists_confirmed %}
            <div class="lists-menu-cards">            
                {% for list in lists_confirmed %}

                {% include 'components/list_card.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-blue1">
                <p>Ainda não existem listas criadas ou seguidas.</p>
            </div>
        {% endif %}        
    </section>

    <section class="white-box lists-menu">
        <div class="lists-menu-title gradient-pink">
            <h1>Convites</h1>
        </div>
        <div class="lists-menu-buttons-container">
            {% if current_user.id == profile_user.id %}
                <form class="lists-menu-buttons-form" method="POST" action="{% url 'appsite:invite_update_all' profile_user.id %}">
                    {%csrf_token%}
                    <input type="submit" class="accept lists-menu-button" name="accept" value="Aceitar tudo" />
                    <input type="submit" class="refuse lists-menu-button" name="refuse" value="Recusar tudo" />
                </form>
            {% endif %}
        </div>
        {% if lists_pending %}
            <div class="lists-menu-cards">            
                {% for list in lists_pending %}

                {% include 'components/list_card_invite.html' with
                    card_id=list.id
                    card_pic=list.picture
                    card_color=list.color
                    card_symbol=list.symbol
                    card_name=list.name
                    prof_user_id=profile_user.id
                    curr_user_id=current_user.id %}

                {% endfor %}
            </div>
        {% else %}
            <div class="lists-menu-empty gradient-pink">
                <p>Sem novos convites por hoje!</p>
            </div>
        {% endif %}
        
    </section>

</article>

{% endblock content %}