accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import CustomAuthForm
from .views import *

app_name='accounts'

urlpatterns = [
    # Sign up & Sign in
    path('', signup, name='index'),
    path('redirect', login_redirect, name='redirect'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('accounts/login/', auth_views.LoginView.as_view(authentication_form=CustomAuthForm), name='login'),

    # Password reset
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # Profile
    path('user/<int:pk>/', UserDetailView.as_view(), name='profile_detail'),
    path('user/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('user/<int:pk>/invite/',      InviteUpdateView.as_view(),    name='invite_update'),
    path('user/<int:pk>/invite/all/',  InviteUpdateAllView.as_view(), name='invite_update_all'),
]

api/urls.py
from django.urls import path

from .views import ListTask

urlpatterns = [
    path('appsite/', ListTask.as_view()),
]

appsite/urls.py
from django.urls import path

from . import views

app_name='appsite'

urlpatterns = [
    ### Profile ###


    path('user/<int:pk>/list/create/', views.ListCreateView.as_view(),      name='list_create'),

    ### List ###
    path('list/<int:pk>/',              views.ListDetailView.as_view(),   name='list_detail'),
    path('list/<int:pk>/update/',       views.ListUpdateView.as_view(),   name='list_update'),
    path('list/<int:pk>/delete/',       views.ListDeleteView.as_view(),   name='list_delete'),
    path('list/<int:pk>/menu/',         views.ListMenuTemplate.as_view(), name='list_menu'),
    path('list/<int:pk>/untrack/',      views.ListUntrackView.as_view(),  name='list_untrack'),
    path('list/<int:pk>/jobs/',         views.JobUpdateView.as_view(),    name='job_update'),
    path('list/<int:pk>/task/create/',  views.TaskCreateView.as_view(),   name='task_create'),
    path('list/<int:pk>/tag/create/',   views.TagCreateView.as_view(),    name='tag_create'),
    path('list/<int:pk>/tag/follow/',   views.TagFollowView.as_view(),    name='tag_follow'),
    path('list/<int:pk>/tag/unfollow/', views.TagUnfollowView.as_view(),  name='tag_unfollow'),

    ### Task ###
    path('task/<int:pk>/update/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),

    ### Tag ###
    path('tag/<int:pk>/add/', views.TagAddView.as_view(), name='tag_add'),
]

opus/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('app/', include('appsite.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('favicon.ico', RedirectView.as_view(url="static/images/favicon.png")), # Fix favicon
]

templates/components/list_card.html
<div class="list-card-wrapper">
    <a href="{% url 'appsite:list_detail' card_id %}">
        <section class="list-card">
            <aside class="list-card-left">
                <img src="{{ card_pic }}" alt="list-card-pic" />
                <div style="background-color: {{ card_color }}" class="list-card-symbol-round">
                    <h2>{{ card_symbol }}</h2>
                </div>
            </aside>
            <div class="list-card-text">
                <h2>{{ card_name }}</h2>
            </div>
        </section>
    </a>
</div>

templates/components/list_card_invite.html
<div class="list-card-wrapper">
    <a href="{% url 'appsite:list_detail' card_id %}">
        <section class="list-card">
            <aside class="list-card-left">
                <img src="{{ card_pic }}" alt="list-card-pic" />
                <div style="background-color: {{ card_color }}" class="list-card-symbol-round">
                    <h2>{{ card_symbol }}</h2>
                </div>
            </aside>
            <div class="list-card-text">
                <h2>{{ card_name }}</h2>
            </div>
            {% if prof_user_id == curr_user_id %}
            <form method="POST" action="{% url 'accounts:invite_update' prof_user_id %}">
                {%csrf_token%}
                <input type="submit" class="action-button accept" name="accept" value="" />
                <input type="submit" class="action-button refuse" name="refuse" value="" />
                <input type="hidden" name="{{ card_id }}" />
            </form>
            {% endif %}
        </section>
    </a>
</div>

templates/components/task_table.html
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>

<script>
    for (const i of {{ tasks_ids }} ) {
        $(document).ready(function(){
            $("#form_task" + i).on("change", "input:checkbox", function(){
                $("#form_task" + i).submit();
            });
        });
    }
</script>

<script>
    function makeRowClickable() {
        if (this.event.target.dataset.href && {{ current_user_job_type }} >= 3) {
            window.location = this.event.target.dataset.href
        }
    }
</script>

{% if current_user_job_type >= 3 %}
    <style>
        tr:not(.header-row) { cursor: pointer }
        tr:hover:not(.header-row) { box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2) }
    </style>
{% endif %}

<table class="table">
    <thead>
        <tr class="header-row">
            {% for tag_name in header %}
                <th>{{ tag_name }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in body %}
            <tr data-href="{% url 'appsite:task_update' row.0 %}" onclick="makeRowClickable()">
                <td>
                    <form id="form_task{{row.0}}" method="POST" action="{% url 'appsite:task_update' row.0 %}">
                        {%csrf_token%}
                        <input type="hidden" value="0" name="{{ row.0 }}" />
                        <input
                            type="checkbox"
                            value="1"
                            name="{{ row.0 }}"
                            {% if current_user_job_type < 3 %} disabled="disabled" {% endif %}
                            {% if row.1 %} checked="checked" {% endif %}
                        />

                    </form>
                </td>
                {% for cell in row|slice:"2:" %}
                    <td data-href="{% url 'appsite:task_update' row.0 %}">
                        <p data-href="{% url 'appsite:task_update' row.0 %}">{{ cell }}</p>
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/components/user_card.html
{% load static %}

<section class="user-card-wrapper">
    <a href="{% url 'accounts:profile_update' user_id %}">
        <button class="user-card-config-button">
            <img class="user-config-cog" src="https://i.ibb.co/PrLfbbR/cog.png" alt="profile-config-icon" />
        </button>
    </a>

    <a class="user-card-link" href="{% url 'accounts:profile_detail' user_id %}">
        <div class="user-card-round-mask">
            <img src="{{ user_picture }}" alt="user-card-pic" />
        </div>
        <div class="user-card-username-wrapper">
            <h2 class="color-light-gray user-card-username">@</h2>
            <h2 class="user-card-username">{{ user_name }}</h2>
        </div>
    </a>

    <h3 class="job-title {{ user_job }}">{% if user_job %} {{ user_job }} {% endif %}</h3>

    <a href="{% url 'logout' %}">
        <button class="blue-button user-card-logout-button">Sair</button>
    </a>
</section>

templates/components/user_picture.html
<div class="profile-pic-mask" style="width: pic_width; height: pic_width;">
    <img src="{{ picture }}" alt="profile-pic" />
</div>